variables:
    CURRENT_HW: "hw06"
    CURRENT_TEST: "testhw06"
    TEST_HASH_EXPECTED: "cc80c0bcacd4939c0ef1738221c6074b481de176358f29a7f75799a7ec9cae8a"



# pre-verify test system hash
before_script:
  - tester="python3 -c 'import base64, lzma; exec(lzma.decompress(base64.b64decode(\"/Td6WFoAAATm1rRGAgAhARYAAAB0L+Wj4AREAg1dAAUbSxPKKmVtGhRPQtvDy44ev3OIPm3q08xy0m1+Vzts/YuDUpfq1D15P9KyY1ltIZb4nnvSxakQAJy1iSkSn0CSwxAcZ9BdnVKenS6RtGMtxaPfI4+FwrOfdwPZUVPktXnaYcFn4bVa3hvnOJxklrrhVHGvvZRTTt4Mu+x20tJgI/iZjgvs5bNDrDOzKuXdEKvEW4gp+6Pog7KU6lzFT7Bco1J73LsxZPv8wmxMVWJHkttShI8lLmJUY1qFo+oH1hvIV90Vm+kC+wYSXLAFlOgRWoxEDNiCGURWFRF64H3VEblJ3rU2fwiIIfQuuUThFY8VteaRJiqhfeuGI/xRCFxKBbqSYvBR6EQlU9Vwu4hgWWgaKsi/9PgdyGCF5+1jcUWk7sxhe9pV/PiSe1Sd2btU+lzwXSw5yJzSVJYLwrnQmJ3dXDnK+isUh9h2pdNpaRwAVeJV3rLSis3ieMU85luyXY4FLPePE3m743a4K35TWlpWLqDCPf0/+BKxfYs7N8E9K4astiojLb+KxvR1+9vz7JxKL4SHa7Vu5KUt1ud3Z2a0oVpJsu0l+rxpxB/s8Lw8HWDHa73U96wovpd32L2iz5S/kLxyOatBRRG8qwaTUSWX6Uaz9mx0sLLCX0BuM0fjrEWrGFrk7X2FAO3PoZCeoCD5UkN8+aDeTBzh3vWNLoawpMlRea7G1EMqBwAAAAAHDy7eLSsmdAABqQTFCAAAt31GR7HEZ/sCAAAAAARZWg==\")).decode())'"
  - TEST_HASH=$(eval "$tester" . tests CMakeLists.txt)

  - echo $TEST_HASH
  - echo $TEST_HASH_EXPECTED
  - if [[ "$TEST_HASH" == "$TEST_HASH_EXPECTED" ]]; then echo "hash ok for tests, CMakeLists.txt"; else echo -n "contents of tests, CMakeLists.txt are not as expected! to fix this, git restore -s upstream/master tests CMakeLists.txt .gitlab-ci.yml"; exit 1; fi

stages:
- compile
- test

# yaml template lol
.job_template: &build_job_artifact
  stage: compile
  cache:
    key: "$CI_JOB_NAME"
    paths:
      - build/

  artifacts:
    name: "$CI_JOB_NAME-$CI_COMMIT_REF_NAME"
    paths:
      - build/
    expire_in: 30 mins


# compile jobs
build-gcc:
  <<: *build_job_artifact
  image: cpp/compiler:2023
  script:
    - mkdir -p build
    - cd build
    - cmake ..
    - make $CURRENT_HW ${CURRENT_TEST} -j4 VERBOSE=1
  tags:
    - linux

build-clang:
  <<: *build_job_artifact
  image: cpp/compiler:2023
  script:
    - mkdir -p build
    - cd build
    - cmake .. -DCMAKE_CXX_COMPILER="clang++" -DCMAKE_CXX_FLAGS="-stdlib=libc++" -DCMAKE_EXE_LINKER_FLAGS="-lc++abi"
    - make $CURRENT_HW ${CURRENT_TEST} -j4 VERBOSE=1
  tags:
    - linux


# test jobs
test-gcc:
  stage: test
  image: cpp/compiler:2023
  script:
    - cd build
    - ctest -R $CURRENT_HW -V -O ctest.log
  dependencies:
    - build-gcc
  artifacts:
    name: "$CI_JOB_NAME-$CI_COMMIT_REF_NAME"
    when: always
    paths:
      - build/ctest.log
    expire_in: 1 year
  tags:
    - linux

test-clang:
  stage: test
  image: cpp/compiler:2023
  script:
    - cd build
    - ctest -R $CURRENT_HW -V -O ctest.log
  dependencies:
    - build-clang
  tags:
    - linux
